config/routes.rb
AlumniApp::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

 root :to => "course#index"

 resources :users do
		collection do 
			get 'login'
			post 'login'
			post 'signup'
			get 'logout'
		end
	end
	
	resources :courses
	
	resources :messages do 
	  resources :comments
	end
	
	resources :events do 
	  resources :comments
	  resources :photos
	  resources :rsvps
	  
	end
	
	get "/feeds/messages", :controller => "feeds", :action => "messages", :format => "atom"

  get "/feeds/messages/:id", :controller => "feeds", :action => "message_comments", :format => "atom"

  get "/feeds/events", :controller => "feeds", :action => "events", :format => "atom"
	resources :notes  do
	 resources :comments
	member do
			get 'download'
			
		end
  end
  
 
	
	resources :photos

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  
  default_scope :order => "created_at DESC"
  
  belongs_to :user
  
  has_many :comments, :as => :commentable
  
  validates :user_id, :presence => true
  validates :title, :presence => true, :length => {:minimum => 5, :maximum => 50}
  validates :body, :presence => true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 
 before_filter :get_message_object, :only=>[:show, :edit, :destroy,:update]
 before_filter :check_logged_in, :only =>
 [:edit,:destroy,:new,:create,:update]
 before_filter :check_user, :only =>
 [:edit,:update]
 
 private
 
 def get_message_object
  @message = Message.find_by_id(params[:id])
  if @message.nil?
    flash[:notice]="Sorry no message was found"
    redirect_to messages_path and return
  end 
 end
 
 def check_user
    if current_user != @message.user
        flash[:error] = "Sorry, The function cannot be performed!"
     redirect_to messages_path and return
    end
 end
 public
 
 def index
   @messages = Message.all
   
 end
 
 def new
  @message = Message.new
 end
 
 def edit
 end
 
 def show
  @commentable = @message
  @comments = @commentable.comments
  @comment = Comment.new
 end
 
 def update
   if @message.update_attributes(params[:message])
    flash[:notice]="Congrats!!! Your changes to the message has been successfully updated"
    redirect_to message_path(@message)
  else
   flash[:error]="Sorry !! Unable to save your changes"
   render :action =>:edit
  end
  
 end
 
 def create
  @message = Message.new(params[:message])
  @message.user_id = current_user.id
  if @message.save
    flash[:notice]="Congrats!!! Your message has been saved Successfully"
    redirect_to messages_path
  else
   flash[:error]="Sorry !! Unable to save your Massage"
   render :new   
  end
 end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%=  form_for  @message  do |f| %>
  <%= f.label :title %><br/>
  <%=  f.text_field :title%><br/>
  
  <%= f.label  "Content"%><br />
  <%= f.text_area :body %><br />
  
  <%= f.submit "Submit" %>
<% end %>

app/views/messages/edit.html.erb
<%=render :partial=>"form"%>

app/views/messages/index.html.erb
<h2 class="title">Messages</h2>
<% if logged_in? %>
  <%= link_to "Create New Message",new_message_path%><br/>
<%else%>
  <%= link_to "Login",login_users_path %>to add message
<% end %>    


<% @messages.each do |message| %>
<div style="padding: 10px; margin: 10px; background-color: #efefef; border: 2px solid #aaa">
  <strong><%=link_to message.title,message_path(message)%></strong>
  
  <br/>
  
  <small>Published on: <%= format_date(message.created_at) %></small>

    <br />
    <small>Published by: <%= message.user.name %></small>


  <%=link_to "Edit",edit_message_path(message)%>
</div>  
<% end %>

app/views/messages/new.html.erb
<%= render :partial=>"form"%>

app/views/messages/show.html.erb
<h2 class='title'>Message Details </h2>
<%= @message.title%><br/>
<%= simple_format(@message.body)%><br/>
<%=link_to "Edit",edit_message_path(@message)%> |
<%=link_to "View all Messages",messages_path%> |
<%= link_to_function "Add Comment","$('#new_comment').show()" %>
<h3>Comments</h3>

<div id="new_comment" style="display: none;background-color: lightyellow; padding: 10px; margin: 10px; border: 2px solid yellow;">
<%= render "comments/form"%>
</div>
<%= render "comments/comments" %>