config/routes.rb
AlumniApp::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

 root :to => "course#index"

 resources :users do
		collection do 
			get 'login'
			post 'login'
			post 'signup'
			get 'logout'
		end
	end
	
	resources :courses
	
	resources :messages do 
	  resources :comments
	end
	
	resources :events do 
	  resources :comments
	  resources :photos
	  resources :rsvps
	  
	end
	
	get "/feeds/messages", :controller => "feeds", :action => "messages", :format => "atom"

  get "/feeds/messages/:id", :controller => "feeds", :action => "message_comments", :format => "atom"

  get "/feeds/events", :controller => "feeds", :action => "events", :format => "atom"
	resources :notes  do
	 resources :comments
	member do
			get 'download'
			
		end
  end
  
 
	
	resources :photos

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  attr_accessible :course_id, :email, :hashed_password, :name, :year_of_passing,:password,:password_confirmation
  
  attr_accessor :password,:password_confirmation
  
  has_many :messages,:dependent => :destroy
  belongs_to :course
  has_many :comments, :as => :commentable
  has_many :events
  has_many :photos
  has_many :notes
  has_many :event_user_mappings
  has_many :events, :through => :event_user_mappings
 
  validates :name, :presence => true
  validates :email, :uniqueness => true, :presence => true, :format => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  validates :password, :presence => true, :confirmation => true
  validates :password_confirmation, :presence => true
  
   def self.authenticate(email, password)
    user = find_by_email(email)
    if user
      if Digest::SHA1.hexdigest(password) == user.hashed_password # i.e. the password provided matches our record
        return user
      else # i.e. the password provided is incorrect
        return false
      end
    else # i.e. the user was not found with the provided email, hence we will return false
      return false
    end
  end

  before_save do
    unless password.blank?
      set_hashed_password
    end
  end
 
  
  private

  def set_hashed_password
    self.hashed_password = Digest::SHA1.hexdigest(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :check_not_logged_in, :only => [:login, :new, :signup]
  
  def login
    if request.post?
       @user = User.authenticate(params[:user][:email], params[:user][:password])
       if @user.is_a?(User)
        flash[:notice]="User logged in Successfully"
        session[:current_user]=@user
        redirect_to courses_path
       else
        flash[:error]="Incorrect email or password. Please try again."
        redirect_to login_users_path
       end
    end
  end
  
  
  def new
    @user= User.new
  end 
  
  def signup
    @user = User.new(params[:user])
    if @user.save 
       flash[:notice] = "Congrats! You've successfully signed up! Please login to continue"
      redirect_to login_users_path
    else
      flash[:error] = "Sorr, we couldn't sign you up because of the following errors!"
      render :action => :new
    end
  end
  
 def logout
  session[:current_user]=nil
  flash[:notice]="You have logged out Successfully"
  redirect_to courses_path
 end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login.html.erb
<h2 class="title">Login</h2>

<div id="login">

<%= form_for :user, :url=> login_users_path  do |f|%>
  
  <%=  f.label :email%><br/>
  <%= f.text_field :email%><br/>
  
  <%= f.label :password%><br />
  <%= f.password_field :password %><br/>
 
  <%= f.submit "Login"%><br/>

<% end %>

</div>

app/views/users/new.html.erb
<h2>New User SignUp</h2>

<div id="signup">
 
  <%= form_for :user,:url => signup_users_path do |f|%>
  
    <%= f.label :name %>:<br />
    <%=f.text_field :name%><br/>
    
    <%= f.label "Course" %>:
    <%= f.select :course_id, Course.all.collect{|c| [c.name,c.id]} %><br />
    
    <%= f.label :email %>:<br />
    <%= f.text_field :email%><br />
    
    
    <%= f.label :password %><br />
    <%= f.password_field :password%></br>
    
    <%= f.label "Confirm Password" %>:<br />
    <%= f.password_field :password_confirmation %><br />
    
    <%= f.submit "Submit" %>
  
<% end %>
</div>