config/routes.rb
AlumniApp::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

 root :to => "course#index"

 resources :users do
		collection do 
			get 'login'
			post 'login'
			post 'signup'
			get 'logout'
		end
	end
	
	resources :courses
	
	resources :messages do 
	  resources :comments
	end
	
	resources :events do 
	  resources :comments
	  resources :photos
	  resources :rsvps
	  
	end
	
	get "/feeds/messages", :controller => "feeds", :action => "messages", :format => "atom"

  get "/feeds/messages/:id", :controller => "feeds", :action => "message_comments", :format => "atom"

  get "/feeds/events", :controller => "feeds", :action => "events", :format => "atom"
	resources :notes  do
	 resources :comments
	member do
			get 'download'
			
		end
  end
  
 
	
	resources :photos

end

app/views/shared/_footer.html.erb
<div id="footer">
  <center>
    The AluminiApp. copyright &copy; <%= Time.now.year %>. All rights reserved.
  </center>
</div>

app/views/shared/_header.html.erb
<div id="header">
<div style="text-align:center"> 
  <h2 class="title">The Alumini Application</h2>
</div>
 <div id="nav">
   <%= link_to "Courses",courses_path, :class => (params[:controller]=="courses" ? "active" : "") %>
   <%= link_to "Messages",messages_path, :class => (params[:controller]=="messages" ? "active" : "")%>
   <%= link_to "Events",events_path, :class => (params[:controller]=="events" ? "active" : "")%>
   <%= link_to "Photos",photos_path, :class => (params[:controller]=="photos" ? "active" : "")%>
   <%= link_to "Notes",notes_path, :class => (params[:controller]=="notes" ? "active" : "")%>
   
   <div id="login_links">
    <% if logged_in? %>
        <%= link_to "Logout", logout_users_path %>
      <% else %>
        <%= link_to "Login", login_users_path %>
        <%= link_to "SignUp", new_user_path %>
      <% end %>
   </div>
 </div>
</div>