config/routes.rb
AlumniApp::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

 root :to => "course#index"

 resources :users do
		collection do 
			get 'login'
			post 'login'
			post 'signup'
			get 'logout'
		end
	end
	
	resources :courses
	
	resources :messages do 
	  resources :comments
	end
	
	resources :events do 
	  resources :comments
	  resources :photos
	  resources :rsvps
	  
	end
	
	get "/feeds/messages", :controller => "feeds", :action => "messages", :format => "atom"

  get "/feeds/messages/:id", :controller => "feeds", :action => "message_comments", :format => "atom"

  get "/feeds/events", :controller => "feeds", :action => "events", :format => "atom"
	resources :notes  do
	 resources :comments
	member do
			get 'download'
			
		end
  end
  
 
	
	resources :photos

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :event_at, :location, :title, :user_id

 
 has_many :comments, :as => :commentable

 belongs_to :user
 has_many :photos
 has_many :event_user_mappings
 has_many :users, :through => :event_user_mappings
 
  
 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :get_event_object, :only => [:show,:edit,:update]
  before_filter :check_logged_in, :only =>
 [:edit,:destroy,:new,:create,:update]
 before_filter :check_user, :only =>
 [:edit,:update]
 
  private
  
  def get_event_object
      @event = Event.find_by_id(params[:id])
      if @event.nil?
       flash[:notice]="Sorry unable to find the event"
       redirect_to events_path
      end
  end
  
  def check_user
    if current_user != @event.user
        flash[:error] = "Sorry, The function cannot be performed!"
     redirect_to events_path and return
    end
 end
 
  public
  
  def index
   @events = Event.all
  end

  def new
   @event = Event.new
  end

  def show
    @commentable = @event
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit
  end
  
  def update
    if @event.update_attributes(params[:event])
     flash[:notice]="Congrats!!! Your changes to the event has been successfully updated"
     redirect_to event_path(@event)
    else
     flash[:error]="Sorry !! Unable to save your changes"
     render :action =>:edit
    end
  end
  
  def create
    
    @event = Event.new(params[:event])
    @event.user_id = current_user.id
    if @event.save
      flash[:notice]= "You have Successfully saved the event"
      redirect_to events_path
    else
      flash[:error]= "Sorry!! Unable to save the Event"
      render :new  
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :title%><br/>
  <%= f.text_field :title%><br />
  
  <%= f.label :description%><br/>
  <%= f.text_area :description%><br />
  
  <%= f.label "Event Schedule"%><br/>
  <%= f.text_field :event_at%><br />
  
  <%= f.label :location%><br/>
  <%= f.text_field :location%><br />
  
  <%= f.submit "Submit" %>
  
  
<% end %> 

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render :partial => "form"%>

app/views/events/index.html.erb
<h1 class="title">Events</h1>
<% if logged_in? %>
<%= link_to "Create New Event",new_event_path %><br/>
<%else%>
  <%= link_to "Login",login_users_path %>to add new Event
<% end %>  
<% if @events.empty?%>
 NO Events found
<% else %> 
 <% @events.each do |event|%>
 <div style="padding: 10px; margin: 10px; background-color: #efefef; border: 2px solid #aaa">
  <strong><%= link_to event.title,event_path(event)%></strong>
   <br/>
  
  <small>Published on: <%= format_date(event.created_at) %></small>

    <br />
    <small>Published by: <%= event.user.name %></small>

 </div>
 <% end %>
<%  end %> 

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render :partial => "form"%>

app/views/events/show.html.erb
<div id="nav">
  <%= link_to "Attendees",event_rsvps_path(@event)%>
</div>


<h2  class='title'>Event Detail</h2>

Title: <%= @event.title%><br/>

Description: <%=simple_format(@event.description)%><br/>

Event Scheduled: <%= @event.event_at %><br/>

Location: <%= @event.location%><br/>

<%= link_to "RSVP",event_rsvps_path(@event),:method => :post %><br/>

<%= link_to "View All Events",events_path%> |
<%= link_to "Edit",edit_event_path(@event)%> | 
<%=link_to_function"Add Comments","$('#new_comment').show()"%> |
<%= link_to_function "Add Photos","$('#new_photos').show()"%>

<h3>Comments</h3>

<div id="new_comment" style="display: none;background-color: lightyellow; padding: 10px; margin: 10px; border: 2px solid yellow;">
<%= render "comments/form"%>
</div>
<%= render "comments/comments"%>

<h3>Photos</h3>
<div id="new_photos" style="display: none;background-color: lightyellow; padding: 10px; margin: 10px; border: 2px solid yellow;">
<%= render "photos/form"%>
</div>
<%= render "photos/photos"%>